theme: jekyll-theme-minimal
title: Chris Abarca's BDA 594 Website
description: This website contains my BDA 594 class projects and assignments.

## ChemicalX

[ChemicalX GitHub Page](https://github.com/AstraZeneca/chemicalx)

This datasheet can help us study the use of drugs and how people interact with them, not only that it can help us predict some of the side effects and help us find better ways to trate people and use medicine.
